/**
 * In-theme names for Heroes & Wizards (fantasy, heroes, wizards, mischief).
 * Used by the start-screen name randomizer.
 */
const THEMED_NAMES = [
  'Aldric the Bold',
  'Bramble Thorn',
  'Corwin Swift',
  'Dusk Weaver',
  'Elara Moonwhisper',
  'Fenric Firehand',
  'Grimble the Clever',
  'Hazel Oakheart',
  'Ivor Stormblade',
  'Jasper the Jester',
  'Kara Quickblade',
  'Luna Stargazer',
  'Morvin the Mugger',
  'Nyx Shadowdancer',
  'Orin Ironbeard',
  'Pippa the Pickpocket',
  'Quinn the Quiet',
  'Ragna the Reckless',
  'Sneaky Sam',
  'Thorn the Thorny',
  'Ursa the Bear',
  'Vex the Vexing',
  'Wulfric Duskaxe',
  'Xander the Xeric',
  'Yara Spellbinder',
  'Zara the Zesty',
  'Archer of the Glen',
  'Baron von Brawl',
  'Captain Clever',
  'Dame Daring',
  'Earl of the East',
  'Freyja the Fair',
  'Grimjaw',
  'Herald of Havoc',
  'Inky the Rogue',
  'Jester of Jests',
  'Knight of Noodles',
  'Lady Luck',
  'Mage of Mischief',
  'Noble Nuisance',
  'Owl-Eyed Owen',
  'Prince of Puns',
  'Quest Queen',
  'Rascal Red',
  'Sir Sasses',
  'Trickster Tim',
  'Unlucky Uther',
  'Viscount Vex',
  'Wandering Wizard',
  'Yonder Yodeler',
  'Zephyr the Zany',
];

export function getRandomThemedName(): string {
  return THEMED_NAMES[Math.floor(Math.random() * THEMED_NAMES.length)]!;
}
